### PR TITLE
Get the actual error stack trace in Google Chrome.

### PR DESCRIPTION
**Pull request by lduchesne**
I was unable to get the error stack trace using Chrome. I only had the error message (not that helpful in itself) and the stack trace from the safeProcess method.

For example, I had:

> TypeError: Cannot read property 'addClass' of undefined(…)
safeProcess @ index.js:251
MessageDispatcher.sendMessage @ index.js:299
MessageDispatcher.sendPendingMessage @ index.js:323
runMessageLoop @ index.js:238

And now I have this:

> index.js:252 TypeError: Cannot read property 'addClass' of undefined
>     at MarkdownCellWidget.onUpdateRequest (widget.js:201)
>     at MarkdownCellWidget.Widget.processMessage (widget.js:445)
>     at safeProcess (index.js:248)
>     at MessageDispatcher.sendMessage (index.js:304)
>     at MessageDispatcher.sendPendingMessage (index.js:328)
>     at runMessageLoop (index.js:238)

### CODE REVIEW

**Comment by sccolbert** [comment]
Chrome will show you the full stack, you just have to click on the ellipsis:
capture
capture

**Comment by sccolbert** [comment]
Also, the project is consolidating repos into `phosphor-core` and `phosphor-ui`. If we want/need to improve anything here, we'll do it here:
https://github.com/phosphorjs/phosphor-core/blob/master/src/messaging.ts

**Comment by lduchesne** [comment]
Thanks for checking this out. As I said, I don't get a useful stack trace in this case (see my previous example). I only get the one from safeProcess! It's not the one from the original error :)

**Comment by sccolbert** [comment]
Did you click on the ellipsis in the original error? The stack should be there on Chrome.

**Comment by lduchesne** [comment]
Ah right, I get it now. Sorry for all the noise :)

**Pull request closed without merging**
